import { KanbanCard, KanbanColumn, ProjectId } from "@t3tools/contracts";
import * as Effect from "effect/Effect";
import * as Option from "effect/Option";
import * as FileSystem from "effect/FileSystem";

import { ProjectionSnapshotQuery } from "../orchestration/Services/ProjectionSnapshotQuery.ts";
import { KanbanRepository } from "../persistence/Services/KanbanBoard.ts";

/** Trivial unix path join — workspaceRoot is always an absolute path. */
function joinPath(base: string, ...rest: ReadonlyArray<string>): string {
  let result = base.replace(/\/+$/, "");
  for (const segment of rest) {
    const trimmed = segment.replace(/^\/+/, "").replace(/\/+$/, "");
    if (trimmed.length > 0) result = `${result}/${trimmed}`;
  }
  return result;
}

/**
 * On every board mutation we snapshot the project's board state to
 * `<workspaceRoot>/.t3/board.md`. Always-on per the user's choice — the
 * file lives next to whatever the agent is working on, gives a
 * grep-able audit trail, and any downstream tooling (TaskMaster,
 * external dashboards) gets a stable text source.
 *
 * Failures are deliberately swallowed (`Effect.ignoreCause`) — a missing
 * workspace root or a write permission error must NOT poison a board
 * mutation. The HTTP route reports the persistence write as success;
 * the markdown export is best-effort cache.
 */
export const writeBoardMarkdownForProject = (projectId: ProjectId) =>
  Effect.gen(function* () {
    const repo = yield* KanbanRepository;
    const snapshot = yield* ProjectionSnapshotQuery;
    const fs = yield* FileSystem.FileSystem;

    const projectShellOpt = yield* snapshot.getProjectShellById(projectId);
    if (Option.isNone(projectShellOpt)) {
      // Unknown project — nothing we can do, but skip silently. The
      // board card has a projectId that isn't in the projection yet
      // (newly created project, perhaps); the next mutation will retry.
      return;
    }
    const projectShell = projectShellOpt.value;
    const workspaceRoot = projectShell.workspaceRoot;
    if (!workspaceRoot || workspaceRoot.trim().length === 0) {
      return;
    }

    const cards = yield* repo.listByProject({ projectId });
    const markdown = renderBoardMarkdown(projectShell.title, cards);

    const targetDir = joinPath(workspaceRoot, ".t3");
    const targetPath = joinPath(targetDir, "board.md");
    yield* fs.makeDirectory(targetDir, { recursive: true });
    yield* fs.writeFileString(targetPath, markdown);
  }).pipe(Effect.ignoreCause({ log: true }));

const COLUMNS_IN_ORDER: ReadonlyArray<KanbanColumn> = [
  "backlog",
  "ready",
  "in_progress",
  "done",
];

const columnLabel: Record<KanbanColumn, string> = {
  backlog: "Backlog",
  ready: "Ready",
  in_progress: "In Progress",
  done: "Done",
};

function renderBoardMarkdown(
  projectTitle: string,
  cards: ReadonlyArray<KanbanCard>,
): string {
  const byColumn: Record<KanbanColumn, KanbanCard[]> = {
    backlog: [],
    ready: [],
    in_progress: [],
    done: [],
  };
  for (const card of cards) byColumn[card.column].push(card);

  const lines: string[] = [];
  lines.push(`# Board — ${projectTitle}`);
  lines.push("");
  lines.push(
    "_Auto-generated by T3 Code on every board change. Read-only; the board is mutated only through Claude in a thread._",
  );
  lines.push("");

  for (const column of COLUMNS_IN_ORDER) {
    const bucket = byColumn[column];
    lines.push(`## ${columnLabel[column]} (${bucket.length})`);
    if (bucket.length === 0) {
      lines.push("");
      lines.push("_No cards._");
      lines.push("");
      continue;
    }
    for (const card of bucket) {
      const prefix =
        column === "done"
          ? "- [x]"
          : column === "in_progress"
            ? "- [~]"
            : "- [ ]";
      const priorityChip =
        card.priority === "urgent"
          ? " `urgent`"
          : card.priority === "high"
            ? " `high`"
            : card.priority === "low"
              ? " `low`"
              : "";
      const reviewChip = card.needsReview ? " `needs-review`" : "";
      const scheduleChip = card.schedule
        ? ` ⏰ every ${card.schedule.minutes}m`
        : "";
      lines.push(`${prefix} **${card.title}**${priorityChip}${reviewChip}${scheduleChip}`);
      if (card.description) {
        for (const descLine of card.description.split("\n")) {
          lines.push(`      ${descLine}`);
        }
      }
      lines.push(`      _id: ${card.id}_`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
