import type { ProjectId } from "@t3tools/contracts";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";

import { WikiReader } from "./Services/WikiReader.ts";
import { ProjectionSnapshotQuery } from "../orchestration/Services/ProjectionSnapshotQuery.ts";

/** Trivial unix path join — workspaceRoot is always an absolute path. */
function joinPath(base: string, ...rest: ReadonlyArray<string>): string {
  let result = base.replace(/\/+$/, "");
  for (const segment of rest) {
    const trimmed = segment.replace(/^\/+/, "").replace(/\/+$/, "");
    if (trimmed.length > 0) result = `${result}/${trimmed}`;
  }
  return result;
}

/**
 * Snapshot the project's wiki to `<workspaceRoot>/.t3/wiki.md`. Mirrors
 * the pattern used by `writeBoardMarkdownForProject` in the kanban
 * module — gives Claude (and external tools) a single grep-able text
 * artifact alongside the SQLite cache.
 *
 * Failures are deliberately swallowed; this is best-effort cache.
 * Skips entirely when the project has no `.almanac/index.db`.
 */
export const writeWikiMarkdownForProject = (projectId: ProjectId) =>
  Effect.gen(function* () {
    const reader = yield* WikiReader;
    const snapshot = yield* ProjectionSnapshotQuery;
    const fs = yield* FileSystem.FileSystem;

    const shell = yield* snapshot
      .getShellSnapshot()
      .pipe(Effect.catchCause(() => Effect.succeed(null)));
    if (!shell) return;
    const project = shell.projects.find((p) => p.id === projectId);
    if (!project) return;

    // Cheap status probe first — bail out cleanly when the wiki isn't
    // initialised so we don't write a stub for projects that never
    // opted in to Almanac.
    const status = yield* reader
      .getStatus(projectId)
      .pipe(Effect.catchCause(() => Effect.succeed(null)));
    if (!status || status.state !== "ready") return;

    const pages = yield* reader
      .listPages({ projectId, limit: 500 })
      .pipe(Effect.catchCause(() => Effect.succeed([])));

    const topicTree = yield* reader
      .getTopicTree({ projectId })
      .pipe(Effect.catchCause(() => Effect.succeed([])));

    const flatTopics = collectTopicSlugs(topicTree);
    const pagesByTopic = new Map<string, string[]>();
    const orphanPages: string[] = [];
    for (const page of pages) {
      if (page.topics.length === 0) {
        orphanPages.push(page.slug);
        continue;
      }
      for (const topic of page.topics) {
        if (!pagesByTopic.has(topic)) pagesByTopic.set(topic, []);
        pagesByTopic.get(topic)!.push(page.slug);
      }
    }

    let body = "";
    body += `# Wiki — ${project.title}\n\n`;
    body += `> Generated by T3 from \`.almanac/index.db\`. Read-only snapshot.\n\n`;
    body += `**${status.health.pageCount} pages · ${status.health.topicCount} topics**`;
    if (status.health.staleCount > 0) body += ` · ${status.health.staleCount} stale`;
    if (status.health.orphanCount > 0) body += ` · ${status.health.orphanCount} orphan`;
    if (status.health.brokenLinkCount > 0) body += ` · ${status.health.brokenLinkCount} broken`;
    body += `\n\n`;

    for (const topicSlug of flatTopics) {
      const slugs = pagesByTopic.get(topicSlug) ?? [];
      if (slugs.length === 0) continue;
      body += `## ${topicSlug}\n\n`;
      for (const pageSlug of slugs) {
        const page = pages.find((p) => p.slug === pageSlug);
        if (!page) continue;
        body += `- **${page.title}** (\`${page.slug}\`)`;
        if (page.summary) body += ` — ${page.summary}`;
        body += `\n`;
      }
      body += `\n`;
    }

    if (orphanPages.length > 0) {
      body += `## (untagged)\n\n`;
      for (const pageSlug of orphanPages) {
        const page = pages.find((p) => p.slug === pageSlug);
        if (!page) continue;
        body += `- **${page.title}** (\`${page.slug}\`)`;
        if (page.summary) body += ` — ${page.summary}`;
        body += `\n`;
      }
      body += `\n`;
    }

    const targetDir = joinPath(project.workspaceRoot, ".t3");
    const targetPath = joinPath(targetDir, "wiki.md");
    yield* fs.makeDirectory(targetDir, { recursive: true }).pipe(
      Effect.catchCause(() => Effect.void),
    );
    yield* fs
      .writeFileString(targetPath, body)
      .pipe(Effect.catchCause(() => Effect.void));
  });

function collectTopicSlugs(
  nodes: ReadonlyArray<{ readonly slug: string; readonly children: ReadonlyArray<unknown> }>,
): string[] {
  const out: string[] = [];
  const walk = (
    list: ReadonlyArray<{ readonly slug: string; readonly children: ReadonlyArray<unknown> }>,
  ) => {
    for (const node of list) {
      out.push(node.slug);
      walk(node.children as never);
    }
  };
  walk(nodes);
  return out;
}
